services:
  jupyter-notebook:
    image: ttimbers/dsci-522-individual-assignment-quarto-python:92da461
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64